[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
legacy = true # Use legacy transactions for networks that do not support EIP-1559

# It is strongly recommended to use environment variables for security.
# You can use either a private key or a mnemonic. Foundry will prioritize the private key if both are set.
#private_key = "${PRIVATE_KEY}"
mnemonic = "${MNEMONIC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

################################################################
#                           CHAIN CONFIG                         #
################################################################

[rpc_endpoints]
merlin-testnet = "https://testnet-rpc.merlinchain.io/"
merlin-mainnet = "https://rpc.merlinchain.io"
dogeos-testnet = "https://dogeos-testnet.unifra.io/v1/${DOGEOS_TESTNET_RPC_KEY}"
dogeos-mainnet = "https://dogeos-mainnet.unifra.io/v1/"

[etherscan]
merlin-testnet = { key = "${MERLIN_TESTNET_L2SCAN_API_KEY}", url = "https://testnet.merlinscan.io/api", chain = 686868 }
merlin-mainnet = { key = "${MERLIN_MAINNET_L2SCAN_API_KEY}", url = "https://scan.merlinchain.io/api", chain = 4200 }
dogeos-testnet = { key = "${DOGEOS_TESTNET_L2SCAN_API_KEY}", url = "https://dogeos-testnet.l2scan.co/api/", chain = 0x5fdaf3}
